// Command bundle regenerates bundle_gen.go from mod.tln and fetches each
// declared plugin, so `go build` compiles them into the tln-plugin binary. It
// is the repo's bundle-install: Core's plugin fetcher (or a local Makefile)
// writes a mod.tln into the checkout and runs `make build`, which runs this.
//
// mod.tln is NOT committed — this repo declares no plugin. Each line:
//
//	plugin "<name>" ["<ref>"] [store] from "<module>"
//
// <name> is what a workflow references (e.g. `connector "solver" via asp`);
// <ref> is the git branch/tag/commit fetched via `go get module@ref` (default
// "latest"); a `store` plugin is a FactStore, wired separately (not here yet).
package main

import (
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"strings"
)

// plugin "<name>" ["<ref>"] [store] from "<module>"
var pluginLine = regexp.MustCompile(`^plugin\s+"([^"]+)"(?:\s+"([^"]+)")?(\s+store)?\s+from\s+"([^"]+)"\s*$`)

type plugin struct {
	name, ref, module string
	store             bool
}

func (p plugin) fetchRef() string {
	if p.ref == "" {
		return "latest"
	}
	return p.ref
}

func main() {
	plugins := parseManifest("mod.tln")

	if err := os.WriteFile("bundle_gen.go", []byte(generate(plugins)), 0o644); err != nil {
		fatal("write bundle_gen.go: %v", err)
	}
	// Fetch each plugin from its source so `go build` can import it. MVS then
	// upgrades tln-language to the version tln-plugin needs across all of them.
	for _, p := range plugins {
		run("go", "get", p.module+"@"+p.fetchRef())
	}
	fmt.Printf("bundle: composed %d plugin(s) into tln-plugin\n", len(plugins))
}

func parseManifest(path string) []plugin {
	src, err := os.ReadFile(path)
	if err != nil {
		fatal("read %s: %v", path, err)
	}
	var out []plugin
	for _, raw := range strings.Split(string(src), "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		m := pluginLine.FindStringSubmatch(line)
		if m == nil {
			fatal("mod.tln: cannot parse %q (want `plugin \"name\" [\"ref\"] [store] from \"module\"`)", line)
		}
		out = append(out, plugin{name: m[1], ref: m[2], module: m[4], store: m[3] != ""})
	}
	return out
}

// generate renders bundle_gen.go: an import per plugin module and a
// bundledPlugins() returning its runtime.Plugin registrations. Store plugins
// are declared but not wired here (that is the FactStore path).
func generate(plugins []plugin) string {
	var imports, regs strings.Builder
	for i, p := range plugins {
		alias := fmt.Sprintf("p%d", i)
		imports.WriteString(fmt.Sprintf("\t%s %q\n", alias, p.module))
		if p.store {
			regs.WriteString(fmt.Sprintf("\t\t// %q is a store plugin — wired via a FactStore, not runtime.Plugin.\n", p.name))
			continue
		}
		regs.WriteString(fmt.Sprintf("\t\t{Name: %q, Factory: %s.Factory},\n", p.name, alias))
	}
	return fmt.Sprintf(`// Code generated by cmd/bundle from mod.tln. DO NOT EDIT.
package main

import (
	"github.com/opentalon/tln-plugin/runtime"
%s)

func bundledPlugins() []runtime.Plugin {
	return []runtime.Plugin{
%s	}
}
`, imports.String(), regs.String())
}

func run(name string, args ...string) {
	cmd := exec.Command(name, args...)
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	if err := cmd.Run(); err != nil {
		fatal("%s %s: %v", name, strings.Join(args, " "), err)
	}
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "bundle: "+format+"\n", args...)
	os.Exit(1)
}
