// Code generated by cmd/bundle from mod.tln. DO NOT EDIT.
// This is the default (no mod.tln present): no bundled plugins.
package main

import "github.com/opentalon/tln-plugin/runtime"

func bundledPlugins() []runtime.Plugin { return nil }
